### Filter

In [4]:
import numpy as np

In [10]:
numbers =np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers>5)

mask= numbers>5
print("Numbers greater than 5:",numbers[mask])
print("Numbers greater than 5:",numbers[numbers>5])

[False False False False False  True  True  True  True  True]
Numbers greater than 5: [ 6  7  8  9 10]
Numbers greater than 5: [ 6  7  8  9 10]


### Fancy indexing VS np.where()

In [18]:
print(numbers)

indiex = [0,2,4]
print(numbers[indiex])

where_result = np.where(numbers>5)
print(where_result)
print("NP Where :", numbers[where_result])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where : [ 6  7  8  9 10]


### Conditional Array instead if else

In [22]:

print(numbers)
condition_array = np.where(numbers>5,numbers*3,numbers*0)
print(condition_array)

condition_array = np.where(numbers>5,True, False)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  0  0  0  0 18 21 24 27 30]
[False False False False False  True  True  True  True  True]
