### Filter

In [4]:
import numpy as np

In [10]:
numbers =np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers>5)

mask= numbers>5
print("Numbers greater than 5:",numbers[mask])
print("Numbers greater than 5:",numbers[numbers>5])

[False False False False False  True  True  True  True  True]
Numbers greater than 5: [ 6  7  8  9 10]
Numbers greater than 5: [ 6  7  8  9 10]


### Fancy indexing VS np.where()

In [18]:
print(numbers)

indiex = [0,2,4]
print(numbers[indiex])

where_result = np.where(numbers>5)
print(where_result)
print("NP Where :", numbers[where_result])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where : [ 6  7  8  9 10]


### Conditional Array instead if else

In [22]:

print(numbers)
condition_array = np.where(numbers>5,numbers*3,numbers*0)
print(condition_array)

condition_array = np.where(numbers>5,True, False)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  0  0  0  0 18 21 24 27 30]
[False False False False False  True  True  True  True  True]


In [1]:
import numpy as np

### Adding and removing data

In [4]:
arr1=np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


#### Array Compatibillty

In [7]:
a= np.array([1,2,3])
b= np.array([4,5,6,7])
c= np.array([7,8,9])

print("Compatibility Shapes :",a.shape == b.shape)
print("Compatibility Shapes :",a.shape == c.shape)

Compatibility Shapes : False
Compatibility Shapes : True


In [13]:
# Array adding column wise and increace row
Orginal_arr = np.array([[1,2],[3,4]])
new_row =np.array([[5,6]])
with_new_row = np.vstack((Orginal_arr,new_row))
print(f"orgnal: {Orginal_arr} \nnew_Row : {new_row} \nWith_new_row : {with_new_row}")

# Array adding row wise and increase column
new_colm=np.array([[7],[8]])
with_new_col=np.hstack((Orginal_arr,new_colm))
print(f"with_new_Colum : {with_new_col}")

orgnal: [[1 2]
 [3 4]] 
new_Row : [[5 6]] 
With_new_row : [[1 2]
 [3 4]
 [5 6]]
with_new_Colum : [[1 2 7]
 [3 4 8]]


In [17]:
# Deleting element from  Array
arr=np.array([1,2,3,4,5,6,7,8])
deleted=np.delete(arr,2)
print(f"Orginal Array : {arr}\nDeleting Element after Array : {deleted}")

Orginal Array : [1 2 3 4 5 6 7 8]
Deleting Element after Array : [1 2 4 5 6 7 8]
