### Leann About numpy

In [1]:
import numpy as np

### Creating Array

In [2]:
array_1d = np.array([1,2,3,4,5])
print("1D Array :",array_1d)

1D Array : [1 2 3 4 5]


In [ ]:
array_2d=np.array([[1,2,3,4],[4,5,6,7]])
print("2D Array :", array_2d)

### List vs numpy array

In [ ]:
py_list = [1,2,3,4,5]
print("Python list multiplication : ",py_list * 2)

np_aray = np.array([1,5,2,6,7]) #element wise multiplication 
print("Python array multiplication : ",np_aray * 2)


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ",time.time()-start)

start = time.time()
np_array = np.arange(10000000) *2
print("\n Numpy operation time: ", time.time() - start)

### Creating array from scratch

In [ ]:
zeros =np.zeros((3,5))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("one array :\n",ones)

full = np.full((2,2),7)
print("full array :\n",full)

randm =np.random.random((2,2))
print("Random array: \n",randm)

sequence = np.arange(0,10,2)
print("Sequence array :\n",sequence)

### Vector , Matrix and Tensor

In [1]:
import numpy as np

vector = np.array([1,2,3])
print("Vector : ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix :",matrix)

tensor = np.array([[[1,2,3], [4,5,6]],
                    [[7,8,9],[10,11,12]]])
print("Tensor :",tensor)

Vector :  [1 2 3]
Matrix : [[1 2 3]
 [4 5 6]]
Tensor : [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array properties

In [12]:
arr = np.array([[1,2,3],[1,2,3]])
print("Shape : ",arr.shape)
print("Dimension : ",arr.ndim)
print("Size : ",arr.size)
print("DType : ",arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
DType :  int64


### Array Reshaped

In [20]:
from numpy import transpose


arr=np.arange(12)
print("Orginal array :", arr)

reshaped=arr.reshape(3,4)
print("Reshaped array : ",reshaped)

flattend = reshaped.flatten()
print("Flattened array :",flattend)

# ravel---> (returns view, instead of view)
raveled = reshaped.ravel()
print("\nReveled array :",raveled) 

transposed= reshaped.T
print("Transpose Array :",transposed)

Orginal array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Numpy Array operations

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing : ",arr[2:7])

print("With Step : ",arr[1:8:2])
print("Negative indexing :",arr[-1])

Basic Slicing :  [3 4 5 6 7]
With Step :  [2 4 6 8]
Negative indexing : 10


In [12]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element : ",arr_2d[2,1])
print("Shape :",arr_2d.shape)
print("Dimension :",arr_2d.ndim) 
print("Entire row: ",arr_2d[1])
print("Entire Column :",arr_2d[:,2])

Specific element :  8
Shape : (3, 3)
Dimension : 2
Entire row:  [4 5 6]
Entire Column : [3 6 9]


### Sorting

In [18]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array :",np.sort(unsorted))

arr_2d_unsorted =np.array([[3,2,1],[7,5,9],[8,6,9]])
print("Sorted 2d array Column wise : ",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2d array Row wise : ",np.sort(arr_2d_unsorted,axis=1))

Sorted Array : [1 1 2 3 4 5 6 9]
Sorted 2d array Column wise :  [[3 2 1]
 [7 5 9]
 [8 6 9]]
Sorted 2d array Row wise :  [[1 2 3]
 [5 7 9]
 [6 8 9]]
